###
# @prompt username
# @prompt password
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###login
# @prompt username 
# @prompt password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### create message
# @prompt senderId
# @prompt content
# @prompt room
# @prompt url
# @prompt type
POST http://localhost:3000/api/v1/send
Content-Type: application/json

{
  "senderId": "{{senderId}}",
  "content": "{{content}}",
  "room": "{{room}}",
  "attachments": {
    "url": "{{url}}",
    "type": "{{type}}"
  }
}

### all messages
GET http://localhost:3000/api/v1/all/general