###
# @prompt username
# @prompt password
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###login
# @prompt username 
# @prompt password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
GET http://localhost:3000/api/v1/users


### send message
POST http://localhost:3000/api/v1/send/69009383c9fc1f9c8e981b36
Content-Type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDA5MzgzYzlmYzFmOWM4ZTk4MWIzNiIsInVzZXJuYW1lIjoicGV0ZXJqb2huIiwiZW1haWwiOiJwZXRzQGdtYWlsLmNvbSIsImlhdCI6MTc2MTczMTAzMiwiZXhwIjoxNzY0MzIzMDMyfQ.SOtSSN-evT0JqqxjG447_G3B5arkBGAJO6nXHT_r_Gc


{
  "text": "hello world",
  "image": ""
}


###
POST http://localhost:3000/api/auth/logout
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDA5MzgzYzlmYzFmOWM4ZTk4MWIzNiIsInVzZXJuYW1lIjoicGV0ZXJqb2huIiwiZW1haWwiOiJwZXRzQGdtYWlsLmNvbSIsImlhdCI6MTc2MTcyNjE5MiwiZXhwIjoxNzY0MzE4MTkyfQ.ctGlv0k6oWX19vTtfBqhht2Tim3bTmeGxcGKVK-BhrA

###
GET http://localhost:3000/api/auth/check
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDA5MzgzYzlmYzFmOWM4ZTk4MWIzNiIsInVzZXJuYW1lIjoicGV0ZXJqb2huIiwiZW1haWwiOiJwZXRzQGdtYWlsLmNvbSIsImlhdCI6MTc2MTcyNjE5MiwiZXhwIjoxNzY0MzE4MTkyfQ.ctGlv0k6oWX19vTtfBqhht2Tim3bTmeGxcGKVK-BhrA